### ISSUE TITLE
dx > d instead of dx>=d

### ISSUE THREAD

**Issue by ALS15204** [jonathanpaulson/AdventOfCode#5]
Hi thank you for posting your solutions to aoc2023 :) 

I have been inspired with your solutions and come by from time to time to check how you code to approach a problem.
Congratulations on maintaining your position on the leaderboard!

In your day 6 implementation, I found a small error in this line:
https://github.com/jonathanpaulson/AdventOfCode/blob/49a2901c16d9941657226893b9bda49f66d19633/2023/6.py#L25

The condition `dx >= d` in the `if` clause would give a wrong answer to Part 1 in the example data.
The correct condition should be `dx > d`.

Just a small detail, and thank you so much again for sharing your solution :clap:

**Comment by jonathanpaulson** [comment]
fixed; thanks!
